name: my_oga_rider
description: A ride hailing platform for drivers to run their own delivery businesses

version: 1.0.3

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^4.0.4
  line_awesome_flutter: ^2.0.0
  image_picker: ^0.8.5+3
  lite_rolling_switch: ^1.0.0
  flutter_otp_text_field: ^1.1.0+2
  otp_timer_button: ^1.1.0
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  cloud_functions: 4.0.13
  firebase_database: ^10.0.9
  google_maps_flutter: ^2.2.3
  location: ^4.4.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  url_launcher: ^6.1.10
  flutter_polyline_points: ^1.0.0
  get_storage: ^2.0.3
  shared_preferences: ^2.0.17
  http: ^0.13.5
  provider: ^6.0.5
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.1.0
  fl_country_code_picker: ^0.0.4
  flutter_local_notifications: ^13.0.0
  flutter_native_splash: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  firebase_storage: ^11.0.10
  flutter_rating_stars: ^1.0.3+4
  percent_indicator: ^4.0.1
  date_format: ^2.0.7
  app_settings: ^4.2.0
  firebase_messaging: 14.3.0
  intl: ^0.17.0
  flutter_dotenv: ^5.1.0
  image:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appicon.png"
  min_sdk_android: 19 # android min sdk min:16, default 21
  adaptive_icon_foreground: "assets/images/appicon_adapt.png"
  adaptive_icon_background: "#ffffff"


flutter_native_splash:
  color: "#f7f6f1"
  image: assets/images/image_light.png
  branding: assets/images/appicon.png
  color_dark: "#272727"
  image_dark: assets/images/image_dark.png
  branding_dark: assets/images/appicon.png

  android_12:
    image: assets/images/image_light.png
    icon_background_color: "#f7f6f1"
    image_dark: assets/images/image_dark.png
    icon_background_color_dark: "#272727"



# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - .env
    #- assets/icons/
    #- images/a_dot_burr.jpeg
    #- images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
