// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwph5iP61uHokKAovxY2PT3TuvMjJkFzE',
    appId: '1:762957034592:android:56d23cf4edd710dab23f05',
    messagingSenderId: '762957034592',
    projectId: 'myoga-80daa',
    databaseURL: 'https://myoga-80daa-default-rtdb.firebaseio.com',
    storageBucket: 'myoga-80daa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzJOb2aev5lTCh2UZt_EgmDD70zuOY0Xw',
    appId: '1:762957034592:ios:f8ddb0d81e351c7ab23f05',
    messagingSenderId: '762957034592',
    projectId: 'myoga-80daa',
    databaseURL: 'https://myoga-80daa-default-rtdb.firebaseio.com',
    storageBucket: 'myoga-80daa.appspot.com',
    androidClientId: '762957034592-1v8m1vg0519pcee2dvpl1d0c4trainnq.apps.googleusercontent.com',
    iosClientId: '762957034592-r3f02bg8gt8085t2u38sftp0qbj8d06v.apps.googleusercontent.com',
    iosBundleId: 'com.myoga.myoga-rider',
  );
}
